### ISSUE TITLE
fliph not working

### ISSUE THREAD

**Issue by mostafaheshammohamed** [Edraak/arabic-mathjax-dev#16]
am trying to add square root in arabic but fliph not working
$$\fliph{\sqrt{5}}$$

**Comment by OmarIthawi** [comment]
@mostafaheshammohamed please use the `\ar` instead:

```
$$\alwaysar{\sqrt{5}}$$
```

Also please consider using the more up to date fork: https://github.com/OmarIthawi/arabic-mathjax

**Comment by mostafaheshammohamed** [comment]
still the sqrt should be flipped
![image](https://user-images.githubusercontent.com/25533537/71346307-473d8380-2570-11ea-9e24-77d6012eb709.png)

**Comment by mostafaheshammohamed** [comment]
ok i used this fork  https://github.com/OmarIthawi/arabic-mathjax and it fixed my problem as omar mentioned
